# Generated by Django 5.2.16 on 2026-08-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(choices=[('NORMAL', 'Normal'), ('OVERLOAD', 'Overload'), ('HIGH_TEMPERATURE', 'High Temperature'), ('HIGH_HUMIDITY', 'High Humidity'), ('COMPOSITE_RISK', 'Composite Risk')], max_length=30)),
                ('mode', models.CharField(choices=[('LIVE', 'Live'), ('HISTORY', 'History')], max_length=20)),
                ('logical_duration_seconds', models.IntegerField()),
                ('sample_interval_seconds', models.IntegerField()),
                ('config', models.JSONField()),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
