# Generated by Django 5.2.16 on 2026-08-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('recorded_at', models.DateTimeField()),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_records', to='products.bag')),
            ],
        ),
    ]
