# Generated by Django 5.2.16 on 2026-08-05 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecyclerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifecyclerecord',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
