# Generated by Django 5.2.16 on 2026-08-11 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0002_remove_sensorreading_strap_strain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('severity', models.CharField(choices=[('NORMAL', 'NORMAL'), ('WARNING', 'WARNING'), ('DANGER', 'DANGER'), ('GOOD', 'GOOD')], max_length=20)),
                ('active_rules', models.JSONField(default=list)),
                ('unavailable_rules', models.JSONField(default=list)),
                ('care_guideline_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_report', to='measurements.measurementsession')),
            ],
        ),
    ]
