# Generated by Django 5.2.16 on 2026-08-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='comparison',
            field=models.JSONField(default=dict),
        ),
    ]
