# Generated by Django 5.2.16 on 2026-08-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('live', 'Live'), ('history', 'History'), ('demo', 'Demo'), ('test', 'Test')], max_length=20)),
                ('seed', models.BigIntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed')], max_length=20)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='products.bag')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='simulation.simulationscenario')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strap_load', models.DecimalField(decimal_places=2, max_digits=6)),
                ('strap_strain', models.DecimalField(decimal_places=4, max_digits=6)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('moisture_detected', models.BooleanField(default=False)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measured_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='measurements.measurementsession')),
            ],
        ),
    ]
