# Generated by Django 5.2.16 on 2026-08-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='strap_strain',
        ),
    ]
