# Generated by Django 5.2.16 on 2026-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementsession',
            name='purpose',
            field=models.CharField(choices=[('live', 'Live'), ('history', 'History')], max_length=20),
        ),
    ]
