# Generated by Django 5.2.16 on 2026-08-15 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_remove_sensorreading_strap_strain'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='material_moisture_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
