# Generated by Django 5.2.16 on 2026-08-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='manufactured_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='purchased_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='model_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='nfc_uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
