# Generated by Django 5.2.16 on 2026-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bag_manufactured_at_bag_purchased_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='model_image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductModel/image'),
        ),
    ]
