# Generated by Django 5.2.16 on 2026-08-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_lifecyclerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='demo_live_scenario_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
